language: php
os: linux
addons:
  sonarcloud:
    organization: "hardyantz-github" # the key of the org you chose at step #3
    token:
      secure: dcf9d5fb7d1ac70ac97b8bc8428e17af4b3d5c2c # encrypted value of your token
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'